Testing
virtual-labs/exp-clipping-line-iiith pull request #8
Opened 2022-06-21 05:37 UTC by KarmanjyotSingh

2022-06-21 17:27 UTC, raj-vlabs requested changes
1. Done a summary review, some basic styling issues are still there like using === instead of ==.
2. Too many global variables are used. 
3. Use switch case when there are more than 3-4 possible options, it has better readability than if-else

2022-06-21 17:27 UTC, raj-vlabs commented on experiment/simulation/css/main.css
> +  width: 101%;
Why is the width 101%? Is this a typo?

2022-06-21 17:27 UTC, raj-vlabs commented on experiment/simulation/index.html
> +                <div style="display: is-flex">
display: is-flex doesn't mean anything, it's either display: flex or class="is-flex". Use the class

2022-06-21 17:27 UTC, raj-vlabs commented on experiment/simulation/index.html
> +                <br />
\<br\> is a deprecated tag. In HTML5, tags are used for defining document structure and css is used for styling. If you need a margin, add it as a css property and not as a line break side effect

2022-06-21 17:27 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +let MESSAGE = "";
Please us upper case naming strictly for constants. regular variables should follow camelCase
Also if you move the declaration of EMPTY before that of message, you can use EMPTY to assign the initial value to message

2022-06-21 17:27 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +    valid = false;
Ar we using a global variable as the effective return value of a function?

2022-06-21 17:27 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +    color = gridColor;
Would this be a valid syntax if color is undefined as you have checked in the condition?

2022-06-21 17:27 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +  if (point1[0] == point2[0]) {
Please use ===

2022-06-21 17:27 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +  return (point2[1] - point1[1]) / (point2[0] - point1[0]);
Are we using global variables for slope calculation here? Please pass in the values as arguments to the function instead of accessing global values

2022-06-21 17:27 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +function highlightEdge(EDGE, width, color) {
EDGE is a regular function argument, please name it using camelCase and not using all capitals

2022-06-21 17:27 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +  if (EDGE === "LEFT") {
Think about using a switch-case since there are too many conditionals here

2022-06-21 17:27 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +  MESSAGE = "";
Please use the EMPTY variable for initialization here

2022-06-21 18:37 UTC, KarmanjyotSingh commented on experiment/simulation/js/main.js
> +    valid = false;
yes , this prevents me writing multiple functions that do the same thing ( validate the form field )

2022-06-21 18:43 UTC, KarmanjyotSingh commented on experiment/simulation/css/main.css
> +  width: 101%;
didnt look at this one, it was the one already set  by the previous team , fixed it

2022-06-22 15:40 UTC, KarmanjyotSingh commented on experiment/simulation/index.html
> +                <br />
have fixed the structure .

2022-06-22 15:43 UTC, KarmanjyotSingh commented on experiment/simulation/js/main.js
> +  return (point2[1] - point1[1]) / (point2[0] - point1[0]);
Actually the return value of this function remains constant all throught maybe I should assign a variable to it and store it once only.

2022-07-10 13:41 UTC, raj-vlabs requested changes
Comments from the previous review have not been resolved. Please make sure that all comments are either resolved or replied to.
Please resubmit for review after resolving all comments.

2022-07-10 13:41 UTC, raj-vlabs commented on experiment/simulation/index.html
> +    <div class="columns is-centered is-flex">
With columns class, you should not need is-flex, please check.

2022-07-10 13:41 UTC, raj-vlabs commented on experiment/simulation/index.html
> +      class="columns is-centered is-variable is-1-mobile is-flex is-flex-wrap-wrap workspace left"
columns and is-flex not needed together, please just use columns

2022-07-10 13:41 UTC, raj-vlabs commented on experiment/simulation/index.html
> +                <div class="mb-3 is-flex">
Please use columns for flexbox functionality where possible

2022-07-10 13:41 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +let MESSAGE = EMPTY;
MESSAGE shouldn't be named as a constant in all capitals.

2022-07-10 13:41 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +    valid = false;
We can use it for now. For future, please make a note that this is a sure-shot recipe for introducing bugs.

2022-07-10 13:41 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +    color = gridColor;
Please resolve this comment from the previous review. All comments should either be marked resolved or responded to.

2022-07-16 12:30 UTC, KarmanjyotSingh commented on experiment/simulation/js/main.js
> +    color = gridColor;
yes , I was just checking out a few things while testing forgot to remove it out , removed now

2022-07-17 15:07 UTC, raj-vlabs approved these changes

2022-07-18 03:27 UTC, merged